# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8CwpFUnEOdINqhylaYJOvUGypNEOTGY
"""

n = int(input("Enter the number of terms: "))
a, b = 0, 1
print("Fibonacci sequence:")
for i in range(n):
    print(a, end=" ")
    a, b = b, a + b