# -*- coding: utf-8 -*-
"""Image_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdlIF7hKlUWmh-lsTNfMgwVQSTpYnegy
"""

# Image Classification using Random Forest
# MyCaptain Assignment

import numpy as np
import os
import cv2
import zipfile
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

print("Upload dataset.zip (dataset/class1, dataset/class2 structure)")
uploaded = files.upload()

# Extract dataset
for file in uploaded:
    if file.endswith(".zip"):
        with zipfile.ZipFile(file, 'r') as zip_ref:
            zip_ref.extractall("/content")

# Load and preprocess images
data = []
labels = []

dataset_path = "/content/dataset"

for label in os.listdir(dataset_path):
    label_path = os.path.join(dataset_path, label)
    for img in os.listdir(label_path):
        img_path = os.path.join(label_path, img)
        image = cv2.imread(img_path)
        image = cv2.resize(image, (64, 64))
        data.append(image.flatten())
        labels.append(label)

data = np.array(data)
labels = np.array(labels)

print("Total images loaded:", len(data))

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    data, labels, test_size=0.2, random_state=42
)

# Train Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Test on a new image (optional)
print("Upload a test image (optional)")
test_upload = files.upload()

for test_file in test_upload:
    test_image = cv2.imread(test_file)
    test_image = cv2.resize(test_image, (64, 64))
    test_image = test_image.flatten().reshape(1, -1)
    prediction = model.predict(test_image)
    print("Predicted Class:", prediction[0])

print("Project completed successfully.")