# -*- coding: utf-8 -*-
"""January2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gs2ytcMHZSdsvi8UCzjokfqiIxKaNghO
"""

print('Hello World!')

