# -*- coding: utf-8 -*-
"""Keras_and_Tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133ilU5Iw-OtiH6YUZ_kfq1NLIChRW2gU
"""

# TEXT GENERATOR USING KERAS & TENSORFLOW
import tensorflow as tf
import numpy as np

# Step 1: Sample Text Data
text = """
Machine learning is fun.
Deep learning is a part of machine learning.
Text generation uses neural networks.
"""

# Convert text to lowercase
text = text.lower()

# Step 2: Create character mappings
chars = sorted(list(set(text)))
char_to_index = {c: i for i, c in enumerate(chars)}
index_to_char = {i: c for i, c in enumerate(chars)}

vocab_size = len(chars)
print("Vocabulary size:", vocab_size)

# Step 3: Prepare input sequences
sequence_length = 40
X = []
y = []

for i in range(len(text) - sequence_length):
    X.append([char_to_index[c] for c in text[i:i + sequence_length]])
    y.append(char_to_index[text[i + sequence_length]])

X = np.array(X)
y = tf.keras.utils.to_categorical(y, num_classes=vocab_size)

# Step 4: Build the model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 50, input_length=sequence_length),
    tf.keras.layers.LSTM(100),
    tf.keras.layers.Dense(vocab_size, activation='softmax')
])

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam'
)

model.summary()

# Step 5: Train the model
model.fit(X, y, epochs=20, batch_size=16)

# Step 6: Text generation function
def generate_text(seed_text, length=200):
    result = seed_text.lower()

    for _ in range(length):
        input_seq = [char_to_index.get(c, 0) for c in result[-sequence_length:]]
        input_seq = np.pad(input_seq, (sequence_length - len(input_seq), 0))
        input_seq = np.array(input_seq).reshape(1, -1)

        prediction = model.predict(input_seq, verbose=0)
        next_index = np.argmax(prediction)
        next_char = index_to_char[next_index]

        result += next_char

    return result

# Step 7: Generate text
print("\nGenerated Text:\n")
print(generate_text("machine learning"))