# -*- coding: utf-8 -*-
"""Positive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9lzfdiy3ecEbm1_hZDLGiXVblcPvjkn
"""

list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Print positive numbers from list1
print("Positive numbers in list1:")
for num in list1:
    if num > 0:
        print(num, end=" ")

print("\n")

# Print positive numbers from list2
print("Positive numbers in list2:")
for num in list2:
    if num > 0:
        print(num, end=" ")